### ISSUE TITLE
No package 'vte-2.90' found

### ISSUE THREAD

**Issue by tejasbhumkar** [zdavkeos/gtkterm#6]
Hello sir!!
I'm not able to configure this program...i'm getting No package 'vte-2.90' found error..i Google it but it shows this package is no longer supported to ubuntu(ubuntu 16.04 i'm using)...i have attached one log file...please let me know if you have any idea.
Thank you!
!
![screenshot from 2018-08-10 11-13-09](https://user-images.githubusercontent.com/29366747/43940689-6d8ca230-9c8e-11e8-852a-4350ea77f28d.png)

**Comment by zdavkeos** [comment]
What version of GtkTerm are you trying to run?

Thanks,
Zach

**Comment by zdavkeos** [comment]
Likely a system configuration issue.
